// init-mongo.js
db = db.getSiblingDB('test');

db.agents.insertMany([
  {
    nom: 'admin',
    prenom: 'admin',
    email: 'admin@admin.com',
    tel: '123456789',
    cin: 'AB111111',
    password: '123',
    genre: 'Home',
    fonction: 'Secrétaire',
    dep_label: '__',
    __t: 'Admin'
  },
  {
    nom: 'chef',
    prenom: 'chef',
    email: 'chef@chef-tri.com',
    tel: '987654321',
    cin: 'XY222222',
    password: '123',
    genre: 'Home',
    fonction: 'Chef de Département',
    dep_label: 'TRI',
    __t:'Admin'
  },
  {
    nom: 'chef',
    prenom: 'chef',
    email: 'chef@chef-fct.com',
    tel: '987654321',
    cin: 'XY222222',
    password: '123',
    genre: 'Home',
    fonction: 'Chef de Département',
    dep_label: 'FCT',
    __t:'Admin'
  },
  {
    nom: 'chef',
    prenom: 'chef',
    email: 'chef@chef-stin.com',
    tel: '987654321',
    cin: 'XY222222',
    password: '123',
    genre: 'Home',
    fonction: 'Chef de Département',
    dep_label: 'STIN',
    __t:'Admin'
  },

  //////////////////////////

  {
    nom: 'OUAHMANE',
    prenom: 'Hassan',
    email: 'ouahmane@tri.com',
    tel: '689531578',
    cin: 'RT875421',
    password: '123',
    genre: 'Home',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'EL HASSANI',
    prenom: 'Sanaa',
    email: 'elhassani@tri.com',
    tel: '68963215',
    cin: 'GH745896',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'EL JOURMI',
    prenom: 'Mohamed',
    email: 'eljourmi@tri.com',
    tel: '689951358',
    cin: 'TE783654',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'AQQAL',
    prenom: 'Abdelhak',
    email: 'aqqal@tri.com',
    tel: '653214897',
    cin: 'AZ789326',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'EL HANNANI',
    prenom: 'Asmaa',
    email: 'elhannani@tri.com',
    tel: '632157824',
    cin: 'QP789532',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'DAHBI',
    prenom: 'Aziz',
    email: 'dahbi@tri.com',
    tel: '632157824',
    cin: 'QP789532',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'KARTIT',
    prenom: 'Ali',
    email: 'kartit@tri.com',
    tel: '6932514875',
    cin: 'MN457896',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'HAIDINE',
    prenom: 'Abdelfatteh',
    email: 'haidine@tri.com',
    tel: '657951248',
    cin: 'VT456565',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'FERTAT',
    prenom: 'Mohammed',
    email: 'fertat@tri.com',
    tel: '69326548',
    cin: 'FZ453698',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'ASSAD',
    prenom: 'Noureddine',
    email: 'assad@tri.com',
    tel: '689578452',
    cin: 'XS459637',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'KALLOUBI',
    prenom: 'Fahd',
    email: 'kalloubi@tri.com',
    tel: '695135624',
    cin: 'LP785421',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'EL BOUJENOUNI',
    prenom: 'Mohamed',
    email: 'elboujenouni@tri.com',
    tel: '678795324',
    cin: 'HY786325',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'HANINE',
    prenom: 'Mohamed',
    email: 'hanine@tri.com',
    tel: '693821754',
    cin: 'ED357951',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'LACHGAR',
    prenom: 'Mohamed',
    email: 'lachgar@tri.com',
    tel: '632154789',
    cin: 'IK136524',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'BAIDADA',
    prenom: 'Chafik',
    email: 'baidada@tri.com',
    tel: '675486214',
    cin: 'WS486235',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'ERRATTAHI',
    prenom: 'Rahhal',
    email: 'errattahi@tri.com',
    tel: '682359851',
    cin: 'AS458963',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'SELMAN',
    prenom: 'Fatimazahra',
    email: 'selman@tri.com',
    tel: '6351425984',
    cin: 'WE789532',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'TRI'
  },
  {
    nom: 'ABOUZAID',
    prenom: 'B',
    email: 'abouzaid@stin.com',
    tel: '695145875',
    cin: 'ER785695',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ABOULMAHJOUB',
    prenom: 'Y',
    email: 'aboulmahjoub@stin.com',
    tel: '698743215',
    cin: 'RE785436',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ASSIF',
    prenom: 'S',
    email: 'assif@stin.com',
    tel: '632154785',
    cin: 'FE736254',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'BELHORA',
    prenom: 'F',
    email: 'belhora@stin.com',
    tel: '693352148',
    cin: 'ZX786952',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL AZZOUZI',
    prenom: 'M',
    email: 'elazzouzi@stin.com',
    tel: '635229815',
    cin: 'EX530124',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL JOUAD',
    prenom: 'M',
    email: 'eljouad@stin.com',
    tel: '602145879',
    cin: 'LA360210',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ELBOUZEKRI ELIDRISSI',
    prenom: 'M',
    email: 'elbouzekri@stin.com',
    tel: '601298371',
    cin: 'RB983560',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'LAASRI',
    prenom: 'S',
    email: 'laasri@stin.com',
    tel: '601823749',
    cin: 'TN093630',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'RAHMANI',
    prenom: 'H',
    email: 'rahmani@stin.com',
    tel: '609351482',
    cin: 'QX302568',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'SADEK',
    prenom: 'M',
    email: 'sadek@stin.com',
    tel: '693524108',
    cin: 'UJ498610',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'SALHI',
    prenom: 'I',
    email: 'salhi@stin.com',
    tel: '608795230',
    cin: 'BR486259',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'YESSARI',
    prenom: 'M',
    email: 'yessari@stin.com',
    tel: '685235971',
    cin: 'BE525635',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ACHAK',
    prenom: 'M',
    email: 'achak@stin.com',
    tel: '602145988',
    cin: 'IP823597',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'AMRANI SOUHLI',
    prenom: 'H',
    email: 'amrani@stin.com',
    tel: '689632561',
    cin: 'DV459632',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'CHAIKHY',
    prenom: 'H',
    email: 'chaikhy@stin.com',
    tel: '685632140',
    cin: 'BQ459632',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL BALLOUTI',
    prenom: 'A',
    email: 'elballouti@stin.com',
    tel: '601245893',
    cin: 'HA783650',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL MOUDEN',
    prenom: 'M',
    email: 'elmouden@stin.com',
    tel: '601478963',
    cin: 'MW753256',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL OTMANI',
    prenom: 'R',
    email: 'elotmani@stin.com',
    tel: '689652314',
    cin: 'PZ014785',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'HAJJAJI',
    prenom: 'A',
    email: 'hajjaji@stin.com',
    tel: '693827145',
    cin: 'RN159632',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'KANDOUSSI',
    prenom: 'K',
    email: 'kandoussi@stin.com',
    tel: '693827145',
    cin: 'YH458963',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'TOUHTOUH',
    prenom: 'S',
    email: 'touhtouh@stin.com',
    tel: '630125894',
    cin: 'KL823651',
    password: '123',
    genre: 'Femme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'BOUTAHAR',
    prenom: 'A',
    email: 'boutahar@stin.com',
    tel: '601578469',
    cin: 'NQ839965',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ABOUOBAIDA',
    prenom: 'H',
    email: 'abouobaida@stin.com',
    tel: '635985624',
    cin: 'BZ145236',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'LAADISSI',
    prenom: 'E',
    email: 'laadissi@stin.com',
    tel: '693398985',
    cin: 'HJ785968',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'HAMMADI',
    prenom: 'L',
    email: 'hammadi@stin.com',
    tel: '614527840',
    cin: 'JP255896',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'KADDAR',
    prenom: 'A',
    email: 'kaddar@stin.com',
    tel: '698574542',
    cin: 'DI102409',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'FAITAH',
    prenom: 'K',
    email: 'faitah@stin.com',
    tel: '635214542',
    cin: 'QW012450',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'LOUALID',
    prenom: 'E',
    email: 'loualid@stin.com',
    tel: '659854730',
    cin: 'CV654789',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'LAHLOU',
    prenom: 'M',
    email: 'lahlou@stin.com',
    tel: '601734558',
    cin: 'WP856930',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ENNAWAOUI',
    prenom: 'C',
    email: 'ennawaoui@stin.com',
    tel: '693021584',
    cin: 'XA863691',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'ALAOUI BELGHITI',
    prenom: 'A',
    email: 'belghiti@stin.com',
    tel: '600124586',
    cin: 'NA966320',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'LOUZAZNI',
    prenom: 'M',
    email: 'louzazni@stin.com',
    tel: '632598751',
    cin: 'MA801937',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL HALOUI',
    prenom: 'Y',
    email: 'elhaloui@stin.com',
    tel: '674123590',
    cin: 'AL749634',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL KHOUDRI',
    prenom: 'M',
    email: 'elkhoudri@stin.com',
    tel: '615999854',
    cin: 'KA012555',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'RIYAD',
    prenom: 'Y',
    email: 'riyad@stin.com',
    tel: '685998654',
    cin: 'NW108017',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL MOUDDEN',
    prenom: 'M',
    email: 'elmoudden@stin.com',
    tel: '677441125',
    cin: 'QK496857',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  },
  {
    nom: 'EL MOUTAKI',
    prenom: 'S',
    email: 'elmoutaki@stin.com',
    tel: '645689652',
    cin: 'AP758965',
    password: '123',
    genre: 'Homme',
    __t: 'Professeur',
    departement: 'STIN'
  }

]);
